version: v1


Agent:
  name: "agent-agni"
  domain: "agni.local.internal"
  forward: 9000
  region: "global"
  certs: 'agni-agent/certs'
  Seeder:
    address: "localhost:8080"
    fingureprint: "2fc5f60dead3a51b86074210c489b437f8f09a053582fce0db3058d79e2292e1"


Router:
  name: "agni-Router"
  router_ip: "127.0.0.1"
  rpc_port: "9000"
  proxy_port: "8000"
  certs: "agni-router/certmanger"
  region: "global"
  dns: "localhost"
  Seeder:
    address: "localhost:8080"
    fingureprint: "2fc5f60dead3a51b86074210c489b437f8f09a053582fce0db3058d79e2292e1"


Nova:
  Seeder:
    address: "localhost:8080"
    fingureprint: "2fc5f60dead3a51b86074210c489b437f8f09a053582fce0db3058d79e2292e1"