version: v1


Agent:
  name: "agent-agni"
  domain: "agni.local.internal"
  forward: 5050
  region: "global"
  certs: 'agni-agent/certs'
  Seeder:
    address: "localhost:8080"
    fingureprint: "021d78cb94755b095d93b30f59d42dcdc8c104cf7e8f758c3b367d844ae53911"


Router:
  name: "agni-Router"
  router_ip: "127.0.0.1"
  rpc_port: "9000"
  proxy_port: "8000"
  certs: "agni-router/certmanger"
  region: "global"
  dns: "localhost"
  Seeder:
    address: "localhost:8080"
    fingureprint: "021d78cb94755b095d93b30f59d42dcdc8c104cf7e8f758c3b367d844ae53911"


Nova:
  name: "agni-Nova"
  port: "9001"
  Seeder:
    address: "localhost:8080"
    fingureprint: "021d78cb94755b095d93b30f59d42dcdc8c104cf7e8f758c3b367d844ae53911"