version: v1


Agent:
  name: "agent-agni"
  domain: "agnistack.in"
  forward: 5050
  host: "localhost"
  region: "global"
  certs: './'
  Seeder:
    address: "45.130.164.217:8080"
    fingureprint: "2992b5706578d0dfea80717e29ef524ac3f9ec7c5fbfe453dfc8fe09dca694ee"
